image:
  file: .gitpod.dockerfile
tasks:
  - init: pip install --no-cache-dir -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
